"""Add reactions models

Revision ID: 06b4cf5343e4
Revises: c5ebefe0fb26
Create Date: 2023-01-09 13:32:08.599830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b4cf5343e4'
down_revision = 'c5ebefe0fb26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
