"""Relationships fixes

Revision ID: 4321d93d106c
Revises: 2ec9bf00740a
Create Date: 2023-01-09 20:09:33.503166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4321d93d106c'
down_revision = '2ec9bf00740a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
