"""Relationship fix

Revision ID: 769081cdc1d5
Revises: 1ed4a11036db
Create Date: 2023-01-09 03:57:12.174114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769081cdc1d5'
down_revision = '1ed4a11036db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
