"""Add original filename

Revision ID: ac14f5176ede
Revises: c85e77a95b2b
Create Date: 2023-01-09 07:13:56.430323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac14f5176ede'
down_revision = 'c85e77a95b2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('original_filename', sa.String(), nullable=True))
    op.create_index(op.f('ix_attachments_original_filename'), 'attachments', ['original_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_original_filename'), table_name='attachments')
    op.drop_column('attachments', 'original_filename')
    # ### end Alembic commands ###
