"""Relationship fix

Revision ID: c85e77a95b2b
Revises: 769081cdc1d5
Create Date: 2023-01-09 04:06:58.480044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85e77a95b2b'
down_revision = '769081cdc1d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
