"""Relationships fixes #2

Revision ID: e88c0953de94
Revises: 4321d93d106c
Create Date: 2023-01-09 20:12:30.736511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88c0953de94'
down_revision = '4321d93d106c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
